### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by bielgiroto** [xerpi/vita-udcd-uvc#53]
The new version is out, the texts at the resolution and fps part here on github should get updated as well, considering that 544p now reaches real 60fps.

That's all, other than that, everything it's working extremely well and even better after 1.5 update, thank you for your time and excellent job @xerpi ! I love your work XD

**Comment by Lulech23** [comment]
A [lot of people](https://www.reddit.com/r/vitahacks/comments/gcsw3q/havent_seen_anyone_post_on_this_udcd_uvc_by_xerpi/) (including myself) still aren't getting 60 FPS at full res, so the current README description is still more accurate to real-world experience. Not sure if anything can be done about it since the plugin already utilizes the Vita for all its worth, but maybe there's still something going on here that can be fixed first?

**Comment by bielgiroto** [comment]
Oh, i'll just close this then
